language: node_js
addons:
  apt:
    packages:
    - xsel
    - xvfb
node_js:
  - '12'
  - '10'

install:
  - npm ci
  - npm run build

script:
  - xvfb-run npm test

jobs:
  include:
    if: branch = master
    - stage: deploy
      script: npm run semantic-release
