language: node_js
addons:
  apt:
    packages:
    - xsel
    - xvfb
node_js:
  - '12'
  - '10'

install:
  - npm ci
  - npm run build

script:
  - xvfb-run npm test

jobs:
  include:
    - stage: release
      node_js: lts/*
      # branch: master #testing before release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
