language: node_js
addons:
  apt:
    packages:
    - xsel
    - xvfb
node_js:
  - '12'
  - '10'

install:
  - npm ci
  - npm run build

script:
  - xvfb-run npm test

deploy:
  provider: npm
  email: me@victorperin.ninja
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: victorperin/qr-scanner-cli
    branch: master
    node: '12'
